name: Nightly build

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure LLVM
        run: ./x.sh configure

      - name: Build LLVM
        run: ./x.sh build

      - name: Package LLVM
        run: |
          tar -czvf llvm-m68k-nightly.tar.gz llvm-m68k-nightly

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: llvm-m68k-nightly-${{ env.DATE }}
          tag_name: llvm-m68k-nightly-${{ env.DATE }}
          files: llvm-m68k-nightly.tar.gz

