name: vlink build

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: vlink version
        required: true
        default: vlink0_18a
      release_tag:
        description: Release tag
        required: true
        default: vlink-0.18a

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download vlink
        run: |
          wget http://phoenix.owl.de/tags/${{ inputs.version }}.tar.gz
          tar -xzf ${{ inputs.version }}.tar.gz

      - name: Build vlink
        run: cd vlink && make

      - name: Package vlink
        run: |
          cd vlink
          mkdir -p package/bin
          cp vlink package/bin
          tar -C package -cf - . | zstd -c -T0 --ultra -20 -o vlink.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          files: vlink/vlink.tar.zst
